# Generated by Django 2.2.12 on 2021-10-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20211027_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='market_price'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(default='', max_length=100, verbose_name='pub'),
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=1, max_length=3, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='title'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
