# Generated by Django 2.2.12 on 2021-10-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='info',
            field=models.CharField(default='', max_length=100, verbose_name='book info'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='book',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='market price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub',
            field=models.CharField(default='', max_length=100, verbose_name='publisher'),
        ),
    ]
